export const LANGUAGE_TO_FLAG = {
  english: "gb",
  french: "fr",
  spanish: "es",
  german: "de",
  italian: "it",
  portuguese: "pt",
  russian: "ru",
  japanese: "jp",
  korean: "kr",
  chinese: "cn",
  arabic: "sa",
  hindi: "in",
  dutch: "nl",
  swedish: "se",
  norwegian: "no",
  danish: "dk",
  finnish: "fi",
  polish: "pl",
  turkish: "tr",
  greek: "gr",
  czech: "cz",
  hungarian: "hu",
  romanian: "ro",
  ukrainian: "ua",
  thai: "th",
  vietnamese: "vn",
  indonesian: "id",
  malay: "my",
  persian: "ir",
  urdu: "pk",
  bengali: "bd",
  tamil: "in",
  swahili: "ke",
};

export const LANGUAGES = [
  "English", "French", "Spanish", "German", "Italian", "Portuguese",
  "Russian", "Japanese", "Korean", "Chinese", "Arabic", "Hindi",
  "Dutch", "Swedish", "Norwegian", "Danish", "Finnish", "Polish",
  "Turkish", "Greek", "Czech", "Hungarian", "Romanian", "Ukrainian",
  "Thai", "Vietnamese", "Indonesian", "Malay", "Persian", "Urdu",
  "Bengali", "Tamil", "Swahili",
];

export const THEMES = [
  "light", "dark", "cupcake", "bumblebee", "emerald", "corporate",
  "synthwave", "retro", "cyberpunk", "valentine", "halloween", "garden",
  "forest", "aqua", "lofi", "pastel", "fantasy", "wireframe", "black",
  "luxury", "dracula", "cmyk", "autumn", "business", "acid", "lemonade",
  "night", "coffee", "winter", "dim", "nord", "sunset",
];
